name: 👷 Build Installer

on:
  workflow_dispatch:
  repository_dispatch:
    types: [octoprint_release]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 👀 Get OctoPrint Version
      id: octoprint_version
      uses: jneilliii/github-action-get-latest-release@master
      with:
        repository: OctoPrint/OctoPrint
        excludes: draft
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 📌 Checkout
      uses: actions/checkout@v4

    - name: 🔨 Install OctoPrint into WinPython
      run: |
        WPy64-31050\Scripts\python.bat -m pip install OctoPrint==${{ steps.octoprint_version.outputs.release }}
      shell: cmd
      
    - name: 🔨 Install LatheEngraver Plugins
      run: |
        WPy64-31050\Scripts\python.bat -m pip install https://github.com/paukstelis/OctoPrint-LatheEngraver/archive/refs/heads/main.zip 
        https://github.com/paukstelis/OctoPrint-Gcode_ripper/archive/refs/heads/main.zip 
        https://github.com/rlogiacco/UploadAnything/archive/master.zip 
        https://github.com/eyal0/OctoPrint-MultipleUpload/archive/master.zip
      shell: cmd
      
    - name: 🔨 Build Installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" /DOctoPrintVersion="${{ steps.octoprint_version.outputs.release }}" "OctoPrint Setup.iss"
      shell: cmd

    - name: 🧹 Delete Existing Release and Tag
      run: gh release delete ${{ steps.octoprint_version.outputs.release }} --cleanup-tag
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 🚀 Create Release and Attach Assets
      uses: softprops/action-gh-release@v2
      with:
        name: "OcotPrint ${{ steps.octoprint_version.outputs.release }} Setup for Windows"
        tag_name: "${{ steps.octoprint_version.outputs.release }}"
        body: "OctoPrint Setup created with Inno Setup using WinPython, winsw, and GitHub Actions."
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: ${{ steps.octoprint_version.outputs.prerelease }}
        files: |
          Output/OctoPrint Setup ${{ steps.octoprint_version.outputs.release }}.exe
